name: Angular CI

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint
      continue-on-error: true

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm run test -- --watch=false --browsers=ChromeHeadless
      continue-on-error: true

  # Trabajo adicional para realizar pruebas e2e si están configuradas
  e2e:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: E2E Tests
      run: npm run e2e -- --headless
      continue-on-error: true
